root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ."
  # Binary file yields from `cmd`.
  bin = "tmp/main"
  # Customize binary.
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  # Watch these directories if you specified.
  include_dir = []
  # Exclude files.
  exclude_file = []
  # This log file places in your tmp_dir.
  log = "air.log"
  # Poll files for changes instead of using fsnotify.
  poll = false
  # Poll interval (defaults to 10ms).
  poll_interval = 1000 # ms
  # It's not necessary to trigger build each time you save a file.
  delay = 1000 # ms
  # Stop running old binary when build errors occur.
  stop_on_root = false
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Delay after sending Interrupt signal
  kill_delay = "0s"

[log]
  # Show log time
  time = true
  # Only show main log (tails to turbomodule/hot-reloading)
  main_only = false

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Delete tmp directory on exit
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true